### ISSUE TITLE
New loading screen

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#245]
For the loading screen we need the ability to add a full screen image. This image will change across deployments.

This issue does not include the logos at the bottom (right now) as there are open questions. 

InVision screen: https://projects.invisionapp.com/d/main#/console/20251865/431780552/preview
The image we'll use for default Canoe: https://invis.io/ZRZ21VFS2HM

Image for default loading screen:
![loading](https://user-images.githubusercontent.com/2395211/96725554-f7417000-137e-11eb-813d-1d95582240df.png)

**Comment by boerwastaken** [comment]
Is there any chance of accomodating elements in there that can represent actual progress? That'd be an UX improvement, because the user would have actionable info; they could see that progress is halted, or that it's a little bit slower than usual, and they could form expectations on when it'd be finished loading.

For instance, 0-100% loaded - for when the total is known up front, and something else for situations in which the extent of things to be loaded is discovered on-the fly. 

Example: https://edutest.temp.build (barebones, hasn't had design resources to make it pretty) where it's a HTML5 Progress element and a bunch of funny squares (white outline when a to-download resource is discovered, filled black when the resource in re is downloaded). The stuff in the progress bar is known from the outset, the stuff related to the squares is not known from the outset; they're created as discovered, and have no size known up front (which is why a progress bar is not used there; a relative display won't work, it'd need to be absolute).

 Log in with `wicher3` as username and a guessable password.

**Comment by katevoss** [comment]
I know that @andrewwapling has been thinking about loading animations but to my knowledge they are not reflective of the actual progress for loading the app. 

@sandroroux or @PeteCoward do you think that we could get or calculate the progress of the initial Canoe download? It would be nice to give users some way of tracking the progress, even if it's not with percentages but somehow represents the actual downloading process, similar to Edutest.

**Comment by sandroroux** [comment]
Yes, we can definitely calculate progress.

In SiteDownloader, something like: `numberOfSuccessfulFetches/(manifest.pages.length + manifest.images.length)`

**Comment by andrewwapling** [comment]
Hi @katevoss @sandroroux , Let me know once you've defined technical requirements, specifications and use case for the loader/s and we can revisit design directions to ensure an effective design solution is implemented. Thanks again, Andy
