### ISSUE TITLE
Guest access in MVP

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#322]
Are we adding access to guests for the MVP? @Juliana-t 
Right now it's not in the `catalpa_canoe` project and thus it's not in the MVP.

**Comment by Juliana-t** [comment]
I am not sure, is that feature part of any existing instance of Canoe? @PeteCoward would like to know your opinion on this as well

**Comment by katevoss** [comment]
Yes, for Haroman we added the ability to login as a guest user. If you go to https://haroman.tl/ and click "Login as a guest", you can demo the experience.

**Comment by boerwastaken** [comment]
For a future in which we want to be able to have e-learning work on devices that have never seen the internet, we will want to offer *some* kind of mode (guest, or unverified self-declared identity, or offline-generated identity) which will allow a user to still see the content.

Since last week we have public key infrastructure in place that (with quite a bit of engineering work) would allow a teacher to generate an identity (account) for some new user while being offline, and for the backend server to recognize these accounts, should a device ever come to see the internet (to sync learning progress).

But for the immediate future we kinda need "guest mode" to work, otherwise a) every device will need to see the internet at least once, to log in, and b) users must not ever, ever, ever log out, lest they be locked out of their learning materials until they can access the net and log in anew.

Think of how utterly frustrating the latter scenario would be. You have the stuff on your phone - you were looking at it a minute ago — but one "wrong move" and you're locked out, dead in the water, for no good reason. I'd throw my phone against a palm tree if that'd happen to me.

**Comment by PeteCoward** [comment]
We're moving to an if you have it you can see it model. The only way you can lose access to content would be by deleting the caches.
Guest mode becomes default not logged in experience.
