### ISSUE TITLE
Failed exam page

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#422]
This is the mockup if someone fails the exam:
https://projects.invisionapp.com/d/main/#/console/20251865/430441886/preview
<img src="https://user-images.githubusercontent.com/2395211/108118416-559c0800-706c-11eb-9cc8-f73a44a154b5.png" width="320">

This is the mockup when they pass:
<img src="https://user-images.githubusercontent.com/2395211/108118517-75cbc700-706c-11eb-86a7-aa20bba45d27.png" width="320">

@andrewwapling Is this the correct mockup? It's odd to have a modal popup when a user fails an exam, and a full screen page when they pass. Also there should be a button to Return to Course in addition to the button to Retake the Exam.

**Comment by andrewwapling** [comment]
Hi @katevoss , Thanks for flagging this. This is an intermediary screen that can act as negative / unsuccessful feedback for users when working through an exam or quiz. We have a positive / successful version of this screen too: 

Intermediary Roll Up (Success): https://invis.io/BZ10396LPHF9
Intermediary Roll Up (Unsuccessful): https://invis.io/R5108ZZ084VP

In terms of a course fail I would recommend utilising the same pattern as above with the following amendments:

• Different image
• No confetti
• Different title & copy
• Change CTA's to as you mentioned above Return to course & Retake the assessment

Even though this is re-using the same pattern I definitely think it's worth adding to the DSM so that we have this screen variant as reference. 

Let me know if you'd like me to mock this up for you now or whether you have everything you need to progress?

Thanks again, Andy

**Comment by andrewwapling** [comment]
Hi @katevoss , As promised please see the fail confirmation screen design for your reference: https://invis.io/52Y02L9YTRF#/447280115_Confirmation_-_Fail

Hope this helps and let me know if you need anything else at all.

Thanks again, Andy

**Comment by megganeturner** [comment]
I think this issue can be closed as this feedback has been addressed as part of the exam review implementation
- updated design: https://projects.invisionapp.com/d/main/#/projects/prototypes/21337919
- pull request: https://github.com/catalpainternational/canoe/pull/679
