### ISSUE TITLE
Opening Canoe, I have a home screen

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#454]
## Conditions of Satisfaction
* I have an option to see a list of Learning Activities
* While I’m using the app, I have the ability to navigate between “Home”, “Learning Activities”, and “Profile”.

## Resources
* Engineering estimate: Day to Days
* Reference design: [Home](https://projects.invisionapp.com/share/6V102V1VURS9#/screens/443710122)

**Comment by PeteCoward** [comment]
OK, the following assumes you are running the [pep_skeleton](https://github.com/catalpainternational/canoe-backend/pull/104) branch of canoe-backend and have migrated your database and created some PeP content ( I just use the canoe-redesign db as a base point to start any work from )

You should be developing this in a branch from the [FT-Offlining](https://github.com/catalpainternational/canoe/pull/377) branch of Canoe.

You should be able to `./run-canoe.sh` and open the home screen and see pretty much what you saw before. 
You should check that the `/manifest/v1` json you retrieve contains references to the PeP pages you created in the CMS.

First thing to do is put a devtools debugger in [Routing.js](https://github.com/catalpainternational/canoe/blob/FT-Offlining/src/js/Routing.js#L29)

That function...
1. reads the url hash
2. Looks to see if it's a simple Canoe page ( settings / profile / login etc. )
3. Ensures we have a manifest ( erroring if it can't find one )
4. Looks to see if the hash is a shortcut to a CMS page, both home and resource list are linked to from the menu so use shortcuts no wagtail page urls.
5. If it is a known shortcut it asks the manifest for the first resourceslistpage or homepage, or whatever type of page the shortcut specifies from the manifest ( for the selected language  )
6. If not a shortcut it asks the manifest to match the given hash to the known hashes and returns that page
7. tells [redux](https://github.com/catalpainternational/canoe/blob/9cd268103538843aba2a11ca5146c546dadc64e0/src/js/redux/ducks/Route.js) about what it has deduced with setRoute

Note: We have moved in the FT-Offlining branch to using the wagtail style urls instead of the ids, which I think is nicer 😛 

Both steps 5 and 6 utilise [getSpecificPage](https://github.com/catalpainternational/canoe/blob/9cd268103538843aba2a11ca5146c546dadc64e0/src/ts/Implementations/Manifest.ts#L218) 
The manifest api endpoint knows only about things that are generic to all page, like hash, version, api_url, children etc. including a `type` string.
That function uses that `type` from what the manifest knows to instantiate.


To get the App.riot.html tag to render the page you will need to...

- [ ] Create a ( really simple for now ) LearningActivityHome type similar to [ResourcesRootPage](https://github.com/catalpainternational/canoe/blob/9cd268103538843aba2a11ca5146c546dadc64e0/src/ts/Implementations/Specific/ResourcesRootPage.ts#L3) ( am considering renaming all the to drop the `Page` suffix and would welcome your thoughts )
- [ ] edit the aformentioned getSpecificPage function to add a new `case` to the switch that instantiates it
- [ ] optionally do this for LearningActivityTopic and LearningActivity too ( will pay off in the next issues )
- [ ] add new riot tag(s?) for the new page type(s?) [here](https://github.com/catalpainternational/canoe/tree/9cd268103538843aba2a11ca5146c546dadc64e0/src/riot/WagtailPages) 
- [ ] edit [App.riot.html](https://github.com/catalpainternational/canoe/blob/9cd268103538843aba2a11ca5146c546dadc64e0/src/riot/App.riot.html#L22) to import the new tag(s?) and add mount point(s?)

My advice is to just get 'Hello I'm { page.title }' working first not worrying too much about the list of topics

See the pattern used in [ResourcesRoot](https://github.com/catalpainternational/canoe/blob/9cd268103538843aba2a11ca5146c546dadc64e0/src/riot/WagtailPages/ResourceArticle.riot.html#L14) for the simplest example of how a wagtail page riot tag read the page from the redux route info.

The page at first may be `.ready = false` ( meaning we know what the manifest knows about it, but not the data from the api.
The routing will have automatically requested that api data, and the page object will update itself to `.ready = true` when more data is available.

The App.riot tag will [update itself](https://github.com/catalpainternational/canoe/blob/9cd268103538843aba2a11ca5146c546dadc64e0/src/riot/App.riot.html#L87) ( and the mounted children ) when this happens, and the onBeforeUpdate handler in the page riot tag will fire allowing you to update this ( maybe hide a loader )

I think that is enough for now :) Enjoy!

**Comment by PeteCoward** [comment]
We really need to check those CoS ( home may actually just be the LearningActivityHome page we are creating here )
That is where the project configurable home may come in. We may have to make the whole bottom nave project configurable.

**Comment by katevoss** [comment]
I second removing the page suffix from the `ts/Implementations/Specific` pages, it's meaningless since all of them end in "page".
