### ISSUE TITLE
JID logo and visual elements for branding Canoe instance

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#499]
# Project brand
- [x] Project name
- [x] Project logotype and versions - @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1K7R3V8ykflro5sjg1PLuMyrjIprPsaUD)
  - [x] White/light backgrounds
  - [x] Dark backgrounds

## Images required for branding Canoe instance
- [x] site logo - @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1K7R3V8ykflro5sjg1PLuMyrjIprPsaUD)
- [x] app icon for mobile home screen @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1K6pgagWPuG91uwBneCmVfELrKLUns00_)
- [x] favicon (as svg) - @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1K2cXcqlk9xu6NuYGiukthyWHPXTv15EI)
- [x] default placeholder for course image - @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1Lyp8W0C73cgLPfZd8EtENi4ELDebYgBB)
- [x] default placeholder for lesson image - @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1LxVZFVyk3tJNA7CN4wrkq17YnXl3jn04)
- [x] default placeholder for exam image - @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1LuxdqM3S42eEtHEGY0Quwn-NNrkd_S1f)
- [x] loading image
  - [x] illustration @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1LrI75xl5eNamczpomR3IwIROl4FnAgcL)
  - [x] UI (with illustration) @andrewwapling https://invis.io/JP10KR0VA748
- [x] login page @andrewwapling https://invis.io/ND10XL747GC6
- [x] finished lesson ('Great job' after finishing with all content in a lesson) @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1Lv9huZ8AgGGgh-TgCTjXwKfZwBwBEMJg)
- [x] submitted feedback @DanielHeads [Link ](https://drive.google.com/drive/u/1/folders/1Lzmqc64VrWMvSIblKqiXQ8b3LgbvDWq1)
- [x] finished course/exam ("Congratulations" card) @DanielHeads [Link](https://drive.google.com/drive/u/1/folders/1Lvti8epM6dP_hJb2_Vpa0IpiWNQ7MWnN)
- [x] logos on the settings screen with the following order @andrewwapling https://invis.io/JP10KR0VA748#/448221869_Profile_-_Settings
  - [x] PNG Department of Health
  - [x] PNG-Aus Partnership
  - [x] JID
  - [x] Catalpa

## Variables - to be defined by design - @andrewwapling  - https://invis.io/JP10KR0VA748
- [x] main active color (buttons, ...)
- [x] button border radius
- [x] top swoop
- [x] bottom swoop

## Resources (for Design only)
- Example -[ issue for branding Canoe instance for Hamahon](https://github.com/catalpainternational/hamahon/pull/182)
- [Logos](https://drive.google.com/drive/folders/1q4FP_KMDmYe38lEqZWYKBPFO9AfZXFCA) @Juliana-t to follow-up with JID to discuss what logos need to be in the app
- [Results from the survey](https://docs.google.com/forms/d/1eTPAeFBgjbNP1br6p8EFllZa3P9IK0uo4M5rpZtzk24/edit#responses)
- Images and design resources (to be added by @DanielHeads when ready)

**Comment by Juliana-t** [comment]
@davidcatalpa @DanielHeads I prepared the issue for the design of the brand for the JID project as well as the elements to brand the project's instance of Canoe, and added it to the Backlog on the Design project board.
Can we start working on that next week?

**Comment by DanielHeads** [comment]
I love it! Thanks @Juliana-t to prepare this.

**Comment by Juliana-t** [comment]
@DanielHeads to work on the brand for the project and visual language for content
@andrewwapling to work on the brand customization of the app, based on the brand work / visual system

**Comment by andrewwapling** [comment]
Thanks for teeing this up @Juliana-t – look forward to progressing this one :)

**Comment by Juliana-t** [comment]
@andrewwapling should we customize the illustration on the screen after the feedback ("Thanks for your feedback...").
Can you also please see if there is any other customization missing in here. Not sure if we need one for the social learning component or if the CTA button was integrating in some other screen
Also, can you please recommend on illustration sizes for:
- congratulation card (after finishing a course)
- after finishing a course card
- eventually for after feedback card?

**Comment by andrewwapling** [comment]
@Juliana-t Yes I believe it would be best from a branding and experience perspective to customise these illustrations to create a tailored experience. Here is a list of the key illustrations used throughout the core DSM that we should consider from a customisation perspective:

• Loading screen
• Login screen
• Fallback imagery for course and lesson cards and course detail hero banner
• Confirmation success
• Confirmation fail
• Feedback confirmation

I believe this covers the core global illustrations. The other places that would benefit from custom JID branded illustrations would be the activity cards. This being said I understand that content creators will create these with varied relevant imagery and illustrations. Though it did occur to me that having a pool of generic JID branded illustrations could have benefit, especially for the overview or start cards.

Hope this helps, Andy

**Comment by andrewwapling** [comment]
Hi @Juliana-t , In terms of the key variables I would recommend the following:

• Button colour (solid and outline): JID primary green colour #14994D
• Button radius: 100% (as per core)
• Tab and toggle highlights: JID primary green colour #14994D
• Top and bottom swoosh device: #F4F8FA to #D9E2E7 linear gradient @ 75 opacity as per core design

Apart from the above we also require fall back generic branded illustration / imagery for all lesson and course cards and to be used as a fall back for course detail hero image areas for each deployment. This is a safety mechanism in case content creators don't upload imagery.

As an example of this please refer to Hamahon solution displaying fall back imagery in the hero banner and lesson cards: https://invis.io/YS10W1WVK23Z

Another example is Canoe DSM: https://invis.io/52Y02L9YTRF#/451214784_Course_Detail_-_Fallback

Hope this helps and sing out with any queries at all.

Thanks again, Andy

**Comment by andrewwapling** [comment]
Hi @Juliana-t , as requested please see below link to the settings screen design direction with partner logo lockup: https://invis.io/JP10KR0VA748

**Comment by Juliana-t** [comment]
Thanks @andrewwapling 
On the fall back imagery, that is all done already (courses, lesson and exam), so we should be good.
For JID we adapt and have a catalogue of images for start cards, objective cards, activity cards, "talk to your team" cards, ... and we are doing our best to have a consistent visual language across all courses and an immersive learning experience.

**Comment by andrewwapling** [comment]
Hi @Juliana-t @DanielHeads, In terms of the login and loading screens it would be great to receive either illustration design direction or recommended illustrations for these screens so that I can mock these up in-situ. Would it be possible to supply these elements and I can create screen designs for these (along with any of the other core screens that require illustration input above?)

I'm assuming we currently have a set style for JID illustrations? Is that correct?

Thanks again, Andy

**Comment by Juliana-t** [comment]
@andrewwapling sure, please coordinate directly with @DanielHeads 
Thanks!

**Comment by DanielHeads** [comment]
Hi @andrewwapling Please check the illustration that I finished today for loading and submitted feedback, if all it's correct I think that my part it's finished. Have a nice day!

**Comment by andrewwapling** [comment]
Hi @DanielHeads @Juliana-t thanks very much for the illustrations. All looks good except I wonder whether it's possible to remove the light green circle from the background of the loader illustration as the tint clashes a bit of with neutral tones? 

Apart from this all good. So that you can see them in context please review the JID theming prototype: https://invis.io/JP10KR0VA748

**Comment by DanielHeads** [comment]
Hi @andrewwapling. Thanks for your help to make things better. The illustration is already in the folder without the circular background. Thanks

**Comment by andrewwapling** [comment]
Hi @DanielHeads @Juliana-t a pleasure, you too :) Thanks so much for this. I have updated the JID theming prototype accordingly, please see: https://invis.io/JP10KR0VA748

Kindly review and let me know if you're happy with the above and sing out if you require any further design support on this one. 

I was thinking it could be good to conduct a design review once implemented @Juliana-t so that we can ensure everything is looking at it's optimum? Let me know your thoughts here.

Thanks again, Andy

**Comment by Juliana-t** [comment]
Perfect! I love that!
Daniel, are you happy with this? Can we move this for frontend
implementation?
Andy sure, once we have it on JID staging, I will ask you to review it and
provide any further feedbacl

**Comment by andrewwapling** [comment]
Excellent glad you like @Juliana-t 

@DanielHeads great point. I agree that it would be excellent to include a more diverse image for the login page. I've just requested access to the link above so that I can integrate this into the UI. Can you please grant me access?

Thanks in advance, Andy

**Comment by pedro16v** [comment]
Being implemented on #671

**Comment by andrewwapling** [comment]
Hi @DanielHeads are you able to please supply all of the JID illustrations as vector SVGs please? We need to use this format as opposed to PNG or WEBP for these types of graphics on the app to achieve both low file size and high quality reproduction. Is that ok to resupply a link with all of these images please? Thanks in advance, Andy

**Comment by Juliana-t** [comment]
@andrewwapling I will have a chat with Daniel later today about this, also note that on the customization – different from what I thought - we don't have a specific fall back images for courses, lessons or exams. What we have is a pack of 5 images that are randomly used as placeholders for courses, lessons and exams. I will work on that with Daniel

**Comment by andrewwapling** [comment]
Hi @Juliana-t thanks very much. After consulting with @megganeturner we determined that SVGs are preferable as we can export out from that point into various formats such as PNG, JPG, WEBP etc. if needed. Plus it gives us the best quality that is scalable due to being vector and low file size with the added bonus of editability and option to create light-weight animation down the track. I'm hoping @DanielHeads originally created these as vector artwork in either Illustrator or Sketch so fingers crossed should be pretty quick to re-export as SVGs.

Regarding the fall back images to confirm yes I believe it's fine to utilise x5 fall back images that can be randomised as a fallback for lesson and course cards. As a general design rule from experience they work better when they are lighter in tone so that control elements and flags sit prominently.

I would then suggest another x5 fallback images that are darker in tone (as a general design rule) that can likewise be used randomly across hero banners for the course detail screen for example. A good example I believe is the Hamahon design direction. Please see mockup and images below for reference:

**Course detail (utilising fallback images for lesson cards and hero banner)**
![Course Detail - Fallback](https://user-images.githubusercontent.com/13824612/118076889-643d5580-b3f6-11eb-8ade-7140c9402d18.png)

**Light patterns (for course and lesson cards)**
![Pattern 1 - Light@1x](https://user-images.githubusercontent.com/13824612/118076926-78815280-b3f6-11eb-81df-895cdd49b839.png)
![Pattern 2 - Light@1x](https://user-images.githubusercontent.com/13824612/118076924-77e8bc00-b3f6-11eb-9e42-ef02afdf8d6e.png)
![Pattern 3 - Light@1x](https://user-images.githubusercontent.com/13824612/118076920-761ef880-b3f6-11eb-8473-e9347f4f2d95.png)
![Pattern 4 - Light@1x](https://user-images.githubusercontent.com/13824612/118076922-77502580-b3f6-11eb-97ce-c2cf4c5463ee.png)
![Pattern 5 - Light@1x](https://user-images.githubusercontent.com/13824612/118076917-74edcb80-b3f6-11eb-8fef-591bf419ea42.png)

**Dark patterns (for hero banner areas)**
![Pattern 1@1x](https://user-images.githubusercontent.com/13824612/118077117-d7df6280-b3f6-11eb-94ea-2dc6985d6b68.png)
![Pattern 2@1x](https://user-images.githubusercontent.com/13824612/118077114-d746cc00-b3f6-11eb-9670-f2b9be1a0d81.png)
![Pattern 3@1x](https://user-images.githubusercontent.com/13824612/118077109-d4e47200-b3f6-11eb-939d-cb07b6fe5c3e.png)
![Pattern 4@1x](https://user-images.githubusercontent.com/13824612/118077110-d6159f00-b3f6-11eb-9993-f25410207330.png)
![Pattern 5@1x](https://user-images.githubusercontent.com/13824612/118077100-d1e98180-b3f6-11eb-838f-016657b22a5d.png)

The current size for these fallback images that seems to be working nicely is square 1:1 ratio 600px x 600px

Hope this helps and drop me a line with any queries.

Thanks, Andy
