### ISSUE TITLE
Error showing after replacing an image

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#522]
## Overview

1. While testing Resources, I uploaded a PNG file to a Basic Card. 
2. Later, I edited the image on Wagtail and replaced it by an image with the same name.
3. After clearing the browser's data and reloading, an error could be seen.

## Resources

* On `https://learn.canoe-redesign.temp.build`
![Screenshot 2021-03-18 at 16 47 15](https://user-images.githubusercontent.com/2813677/111590641-b5233a00-8809-11eb-864c-8ef39803ad3f.png)

* On `https://learn2.canoe-redesign.temp.build`
![Screenshot 2021-03-18 at 16 47 28](https://user-images.githubusercontent.com/2813677/111590625-af2d5900-8809-11eb-9b44-0ac0ba357878.png)

**Comment by pedro16v** [comment]
Deleting the resource using that image seems to mitigate the problem.

**Comment by boerwastaken** [comment]
Possibly related:
https://github.com/catalpainternational/canoe-backend/blob/9469bf6470796bd079fbcf766eb93761d011add9/elearning_content/views.py#L51:L57

**Comment by boerwastaken** [comment]
Nope, that's not related, the manifest is properly getting a fresh etag when I update an image (uploading a new image file into the image resource, or even uploading the same file into it).

**Comment by boerwastaken** [comment]
Question: Do you know why you get "No manifest found"? It looks like that is some frontend code spewing that out in the place where the image is supposed to be? And why three times?
Anyway it's lying (and three times at that!) as without a manifest it could've never discovered the filenames of the renditions it says are missing. On top of that it should be doing its logging/lying in the JS console rather than in the content, this looks like a 90s PHP page! :clown_face: 

> Later, I edited the image on Wagtail and replaced it by an image with the same name.

Do you mean you replaced the image node (the "wagtail image object") with one having the same name (same title)? Or do you mean you uploaded a file into the existing "wagtail image object"? Note that Django out of the box doesn't overwrite existing (potentially orphaned) image files, instead you'd get the contents under a variation of the original filename as supplied by the browser. That variation could well be the `_4IzhUMF` suffix you're seeing.

The server actually has the image referenced in the manifest (I checked whether the file exists on the backend). So, the manifest is correctly referencing the image. This looks like a frontend coherency problem - since you mention you're running into this on a fresh load ("after clearing the browser's data and reloading" — which state categories did you nuke, exactly?), perhaps the problem lies in that the page/card/thing is not sufficiently aware that the referenced image hasn't been precached (yet) — I think in that case it should do something else than losing its marbles.

**Comment by katevoss** [comment]
@boerwastaken the "no manifest found" error comes [from here](https://github.com/catalpainternational/canoe/blob/7834387265a52ba46093b4d5e0835a731f6b7b6c/src/js/Routing.js#L52). The errors accumulate until you refresh the page which is why you see 3 (I think). I agree that this should be logged to the JS console, what do you think @md8n ?

**Comment by md8n** [comment]
The "no manifest found" is what happens when there's an exception being thrown further down in the code. Normally it's being caused by JS errors in some riot tag or other.

**Comment by pedro16v** [comment]
> Do you mean you replaced the image node (the "wagtail image object") with one having the same name (same title)? Or do you mean you uploaded a file into the existing "wagtail image object"?

I clicked `Choose file` and picked another image. This "another image" was actually the same image but slightly edited.

![Screenshot 2021-03-19 at 11 27 48](https://user-images.githubusercontent.com/2813677/111722985-34fee200-88a6-11eb-9562-461b6f43a85c.png)

**Comment by md8n** [comment]
OK, I've managed to replicate this locally. There's a handful of things to fix.

1. Using `embed` or `image` in the `Content` type has been deprecated. Use the `Basic` type instead to show an image.  This isn't the cause of this bug, but it is a first step for cleaning things up.
2. The `ImageWrapper.riot.html` was not gracefully handling problems when the image couldn't be found, or when the correct rendition of an image couldn't be found.
3. The 'No manifest found' error message is almost always triggered by some bug or exception in a riot tag, not by there being 'no manifest found'. So it needs correction.
4. When the above error condition occurs `Routing.js` routes to `error`, but we don't have any riot tag defined for `error`.

**Comment by PeteCoward** [comment]
I have a way to fix this in the backend, working on it...

**Comment by pedro16v** [comment]
@PeteCoward Not sure if this is the same problem.

Found it [on this card](https://learn.canoe-redesign.temp.build/#/site/home/course/lesson-1:content:8).

![Uploading Screenshot 2021-03-24 at 17.47.53.png…]()

**Comment by pedro16v** [comment]
So, now all we have is a [_nicer_ error](https://learn.canoe-redesign.temp.build/#/site/home/learning-about-descriptions/yellow:content:2).

![Screenshot 2021-03-30 at 16 05 06](https://user-images.githubusercontent.com/2813677/112947460-c9ecbf80-9171-11eb-958d-75104fa65406.png)
