### ISSUE TITLE
Resources page: trying to do a search throws an error

### ISSUE THREAD

**Issue by md8n** [catalpainternational/canoe#555]
# Description

On the resources page try to use the search box to find a resource.  It will throw this error:
![image](https://user-images.githubusercontent.com/1767870/112807123-81ba9800-90b2-11eb-975f-91cebfea147c.png)

**Comment by katevoss** [comment]
This error is caused by the change in loading the list of resources so that only the resource title is available, not the description (or type). Once you open a resource, then the description and type are available and the description is searchable on the Resources List. 

To fix this in the short term, I can remove the description from the search criteria. The better fix is to make the resource description and card type available on page load.

**Comment by pedro16v** [comment]
I can still see this on https://learn.canoe-redesign.temp.build/#resources
