### ISSUE TITLE
End of Lesson/Course actions

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#753]
Hi @Juliana-t and @andrewwapling ,

Actions at the end of Lessons and Courses seem to have a few consistency issues. 

Can we create a definitive rule for:
* Primary button style
* Secondary button style
* How many actions are possible at the end of each section
* Which actions are those?

---

### This is what can be found by using the latest Bero

**Lesson complete can have:**
* As primary actions
  * Next lesson
  * Take exam / survey
* As secondary actions
  * View resources
  * Join the discussion
  * Back to course

**Course complete can have:**
* As primary actions
  * Back to Courses
* As secondary actions
  * View resources
  * Join the discussion

**Comment by Juliana-t** [comment]
At least on Kumul Helt Skul I can see some inconsistency in navigation/screens after course or lesson completion.

Let me see if I can clarify it:

## Lessons

### If there are more lessons not yet completed in the course
* Primary button
  * Next lesson (should take to next lesson and not to the course details page)
* Secondary button
  * Join the discussion (if there is at least 1 discussion topic for this lesson)
  * Back to course

### If all lessons in the course were completed
#### if there is an exam / survey for the course
* Primary button
  * Take exam / survey 
  AND
  * Join the discussion (if there is at least 1 discussion topic for this lesson)
* Secondary button
  * Skip (takes user to XXXX)

#### if there isn't an exam / survey but there is at least 1 discussion topic for this lesson
* Primary button
  * Join the discussion 
* Secondary button
  * Skip (takes user to XXXX)

#### if there isn't an exam / survey neither any discussion topic for this lesson
* Primary button
  * 'Complete course' (takes user to XXX) 

## Courses
A course is completed after a user completes all lessons AND the exam / survey (in casa there is one)
### Course completed can have:
* Primary button
  * Back to Courses
* Secondary button
  * View resources (if at least 1 resource is available in this instance of Bero)
  * Join the discussion (if at least 1 lesson on the course has at least 1 discussion topic associated)

@andrewwapling I will leave it for you to clarify the different styling for each type of button

**Comment by pedro16v** [comment]
I see possibilities where multiple primary and multiple secondary actions may occur 😱 

@andrewwapling to the rescue! 😅

**Comment by andrewwapling** [comment]
Hi @pedro16v @Juliana-t just getting back around onto this one which somehow fell off my radar. As you have started above I think we need to firstly determine each user story for every confirmation screen scenario and design to these as I understand there could be many permutations.

In doing this we may also be able to define opportunities for uplifting the confirmation screens to support an additional call to action element that can be present if needed. I'm thinking this could be suitable for adding an extra nudge for functionality such as the social learning aspects or anything else we deem appropriate.

I've rationalised, tweaked and added the confirmation screens that we have currently included in Bero core (and Exam Review flow) so that we can kickstart the process of understanding each possible user story. I've distilled each confirmation screen design into consistent fields that outline headline copy, body copy and primary and secondary call to action links (and proposed next best actions), along with the current state designs. Each confirmation screen also has the option for a custom illustration or image that sits at top of screen and helps weight the screen, engage the user and create context for the content below.

My feeling that x2 call to actions are best for focus, with the possibility of being able to add an additional component to highlight another action. This being said it raises the question of where there are multiple CTA's that could be relevant to a confirmation screen could or should we give content moderators the ability to customise these? Or is it best to keep this locked down? Where we have the option of a discussion CTA or a resources CTA my feeling would be that the social learning aspect would trump resources. Interested in thoughts here?

Hope this is helpful! Kindly review and let me know your thoughts. If we identify additional use cases or variants of these let's document these and design for them to ensure the flows are thought through and make sense from a UX perspective.

===

**Lesson completion:**
Headline: Good job [Insert Name]!
Copy: You just completed Lesson Name successfully. Only {one} more lesson to go to complete Course Name.
Primary CTA: Next lesson [next lesson in course series]
Secondary CTA: Join the discussion [discussion tab anchored open for the course in question] *This is an important pathway to boost affordance of the Discussion tab within the course detail screen
Design direction link: https://projects.invisionapp.com/share/RG11E66RZBUH

**Course completion:**
Headline: Amazing work [Insert Name]!
Copy: You just completed Course Name successfully. Start another course or dive into the course discussion.
Primary CTA: Back to courses [back to course listing screen]
Secondary CTA: Join the discussion [discussion tab anchored open for the course in question] *This is an important pathway to boost affordance of the Discussion tab within the course detail screen
Design direction link: https://projects.invisionapp.com/share/B211E66UN3AS

**Last lesson completion (exam flow):**
Headline: Amazing effort [Insert Name]!
Copy: You just completed the last lesson in Course Name successfully. You're now ready to undertake an exam to validate your learning.
Primary CTA: Commence exam [start exam flow]
Secondary CTA: Join the discussion [discussion tab anchored open for the course in question] *This is an important pathway to boost affordance of the Discussion tab within the course detail screen
Design direction link: https://projects.invisionapp.com/share/BQ11E66Z6WD2

**Review exam (general no percentage):**
Headline: You almost did it [Insert Name]!
Copy: You didn’t complete this exam successfully. You can review your exam now with the option to retake it.
Primary CTA: Review exam [start exam review flow]
Secondary CTA: Back to courses [back to course listing screen]
Design direction link: https://projects.invisionapp.com/share/ZK11E678UCWG

**Review exam (percentage):**
Headline: You scored 33%  <br/>Keep trying [Insert Name]!
Copy: You didn’t complete this exam successfully. You can review your answers now or retake the exam.
Primary CTA: Review your answers [start exam review flow]
Secondary CTA: Retake exam now [start exam flow]
Design direction link: https://projects.invisionapp.com/share/E611E67UKFG3

**Retake exam:**
Headline: Are you ready to retake your exam [Insert Name]?
Copy: You have the opportunity to retake  the exam now and achieve a successful outcome. Alternatively you can return  to the course.
Primary CTA: Retake exam [start exam flow]
Secondary CTA: Back to course [back to course detail screen]
Design direction link: https://projects.invisionapp.com/share/3H11E687B647

===

**Comment by pedro16v** [comment]
Thank @andrewwapling for your _very_ comprehensive take on this. Let's see if we can keep up:

> My feeling that x2 call to actions are best for focus, with the possibility of being able to add an additional component to highlight another action. This being said it raises the question of where there are multiple CTA's that could be relevant to a confirmation screen could or should we give content moderators the ability to customise these? Or is it best to keep this locked down? Where we have the option of a discussion CTA or a resources CTA my feeling would be that the social learning aspect would trump resources. Interested in thoughts here?

* Agreed. Personally I always liked the two options (big main vs small secondary). Catering for a third isn't ideal but seems to be needed sometimes.
* Giving content moderators the ability to customise which CTAs show up sounds onerous. For users and possibly from an engineering perspective too.
* Discussions seem to be what people are after. We haven't seen anyone using Resources so far. **I see the possibility for us to remove that CTA altogether.**

---

Reviewing your new screens I noticed there's a "Review exam" and "Review your answers". Isn't this the same? That aside, the navigation options sound correct to me (I made sketch to visualise it but it's too confusing to share 😅 ).

**Comment by pedro16v** [comment]
> We haven't seen anyone using Resources so far
Juliana tells me I **lied**. Resources ARE being used on Kumul Helt Skul. But I keep my opinion on not keeping that CTA.

**Comment by andrewwapling** [comment]
Hi @pedro16v thanks for the intel here! Just confirming the only difference between the two review confirmation screens above are that one is explicit about the exam result percentage whilst the other is not. Perhaps we can defactor the general one 'Review exam (general no percentage)'. What do you think?

**Comment by pedro16v** [comment]
That sounds correct. I think we'll always want to show the score. @Juliana-t ?

**Comment by Juliana-t** [comment]
Yes, that is correct! Those are 2 separate moments (as a reference you can
see the ED Course 2 on KHS), user is informed when a lesson is completed
(positive reinforcement) and the user is informed when a course is
completed. A course is completed when: 1) all lessons of a course are
completed and the course has no exam associated, 2) all lessons of a course
are completed + exam is completed with at least the min score. On both we
want to provide positive feedback and reinforcement. Although, if a user
scored between min rate and 99%, they will also have the option to review
wrong answers and retake the exam.
So we need to show score (Result of the exam), in the completion of any
course that encompass an exam

**Comment by pedro16v** [comment]
Great, I'll spin up a new issue to implement these changes soon.

**Comment by Juliana-t** [comment]
@andrewwapling I think the course (with exam) completion is missing. On that one, users are congratulated, told how much they score and invited to:
- review and retake (to improve their score)
- go back to the courses screen, and star a new course

**Comment by pedro16v** [comment]
@Juliana-t adding to that, I seem to remember a rule where people who score 100% aren't invited to review or retake the exam. Everyone that passes and scores up to 99% will see that option.

I really have to get that knowledge base started to include information like this (on my to do...)

**Comment by Juliana-t** [comment]
That is correct Pedro.
who scored 100% are not invented to review/retake. Those with scores
between min passing score and 99% would have the option to review/retake

**Comment by andrewwapling** [comment]
> @andrewwapling I think the course (with exam) completion is missing. On that one, users are congratulated, told how much they score and invited to:
> 
> * review and retake (to improve their score)
> * go back to the courses screen, and start a new course

@Juliana-t this one has been updated as per above:

**Review exam (percentage):**
Headline: You scored 33% 
Keep trying [Insert Name]!
Copy: You didn’t complete this exam successfully. You can review your answers now or retake the exam.
Primary CTA: Review & retake exam [start exam review flow]
Secondary CTA: Back to courses [back to course listing screen]
Design direction link: https://projects.invisionapp.com/share/E611E67UKFG3

**Comment by Juliana-t** [comment]
Perfect @andrewwapling 
I am just not sure about the wording and what information goes to the title/text description. I added my comments on invision and would also like to hear from @KaraChesal . Design is great, I am just not 100% sure about the text and the hierarchy of the information, I think we can be more constructive by displaying the info in a more positive way

**Comment by andrewwapling** [comment]
Thanks for your feedback @Juliana-t – I agree it would be great to maintain a positive, friendly and supportive tone throughout the copy. As you say we have the design pattern to accomodate it so would be interested in @KaraChesal's input here in terms of copy. In the meantime let me know if you require any additional design support on this one.

**Comment by KaraChesal** [comment]
Yes, where does it make sense to draft some options? I am not sure what all the permutations are here. But happy to provide input and align it to the formative assessment text in PeP.

**Comment by pedro16v** [comment]
> Yes, where does it make sense to draft some options? I am not sure what all the permutations are here. But happy to provide input and align it to the formative assessment text in PeP.

I've been trying to put this together for almost a week now 😓 I'll ping you when I have something you all can act on.

**Comment by andrewwapling** [comment]
Ok great thanks @KaraChesal :) @pedro16v where would be best for this? In the GitBook that you most excellently kicked off for the Bero content guide distillation?

**Comment by pedro16v** [comment]
@Juliana-t @andrewwapling @KaraChesal it took me a while but I finally was able to glue it all together. Please check #973   for a continuation of Andy's work (and be in awe in the famous Pedro's sketches ™)

**Comment by pedro16v** [comment]
Closing in favour of #973
