### ISSUE TITLE
Safari Video Playpack

### ISSUE THREAD

**Issue by andrewcatalpa** [catalpainternational/canoe#778]
Looks like we have an issue with Safari on MacOS not able to playback videos on Bero. Here's the URL I'm testing https://kumulheltskul.com/#/site/learn/course-3-triage/lesson-1-the-interagency-integrated-triage-tool-iitt:content:6

![2021-06-30_15-34-11](https://user-images.githubusercontent.com/86705107/123907493-58631e00-d9b9-11eb-85f7-e6dfd34ca439.png)

**Comment by PeteCoward** [comment]
works for me on Safari `Version 14.0.3 (16610.4.3.1.7)`
video referenced is https://admin.kumulheltskul.com/media/media_transcodes/3-H264-480p-20q.65g7psl4.mp4

it has a black screen poster ( the auto thumbnailer chooses the first video frame i think, which is black )

@andrewerbs what browser version are you using, and do you see anything in the console log?
I can ask a few other safari users to test it too

**Comment by andrewcatalpa** [comment]
No worries, I’m using Safari 13.1.3

**Comment by PeteCoward** [comment]
> No worries, I’m using Safari 13.1.3

That version should still support that format though

**Comment by pedro16v** [comment]
@andrewcatalpa we've had a number of video-playing fixes that might not have reached production yet. Might be worth for you to test that on the [staging site](https://jid-staging.temp.build/) too.

**Comment by pedro16v** [comment]
I just tried it using Safari Version 14.1 (16611.1.21.161.6). It does not work both in staging and production. It works fine using Chrome and Firefox.

If I scrap the [video URL](https://admin.kumulheltskul.com/media/media_transcodes/13-H264-480p-20q.nwmtcohr.mp4) from the HTML and open it on a new tab, it does work 🤔

**Comment by pedro16v** [comment]
I found others having problems with `mp4` on `video` tags on Safari too. https://stackoverflow.com/questions/27712778/video-plays-in-other-browsers-but-not-safari

**Comment by boerwastaken** [comment]
> it has a black screen poster ( the auto thumbnailer chooses the first video frame i think, which is black )

[It seeks to 10%](https://github.com/dirkvdb/ffmpegthumbnailer#usage).

**Comment by boerwastaken** [comment]
What happens if you disable/bypass the serviceworker in one of those Safaris that exhibits the problem?

**Comment by pedro16v** [comment]
> What happens if you disable/bypass the serviceworker in one of those Safaris that exhibits the problem?

The only way I got that to work in Safari was to empty caches and reload the very same page containing the video. On the first and fresh page load, the video will work. If I navigate away and back, then I'm back to the crossed over play button.

The Safari developer tools have an option under Network to ignore caches but still, it will load the video from the Service Worker. Someone better than me might actually know what to do here.

**Comment by boerwastaken** [comment]
> The Safari developer tools have an option under Network to ignore caches but still

I haven't Safari'd in decades, but in general browsers nowadays have two types of cache: the transparent one, which used to be a browser-wide instance (but that's changing because of cache-timing deanonymization attacks), and site-specific caches which can actually be manipulated "from within the site" (those we use to store Bero content, and that's also where the serviceworker dumps stuff).

The config panel in your Safari may have been referring to just the former cache variant.

**Comment by boerwastaken** [comment]
> The only way I got that to work in Safari was to empty caches and reload the very same page containing the video. On the first and fresh page load, the video will work. If I navigate away and back, then I'm back to the crossed over play button.

That could indicate a problem with the Bero service worker.

**Comment by PeteCoward** [comment]
Trying hard to reproduce on iPhone, but it seeems to work fine for me

**Comment by pedro16v** [comment]
This issue is originally about **Safari** on **MacOS**. However, I can now reproduce it too on **Safari** on **iOS**

My versions are:
* Safari 14.1 on MacOS 11.3.1
* Safari on iOS 14.6 

Here's how I was able to reproduce this in a constant way @PeteCoward:
1. Open a Safari private window
2. Go to `kumulheltskul.com`
3. The site should ask you to log in
4. Open `ED Course 3 - Triage` and then `Lesson 1 - The Interagency Integrated Triage Tool (IITT)`
5. Navigate your way to card 6. The video should be playable (if not, close the private tab and start from 1)
6. Reload the website. The video isn't playable anymore (you can see the play icon with a diagonal bar over it)

---

While doing this, here's what I could see on the developer tools (filtered by `mp4`):

#### 1. When the video successfully loads

After page load
<img width="898" alt="Screenshot 2021-07-12 at 10 02 54" src="https://user-images.githubusercontent.com/2813677/125264329-abaf6780-e2fb-11eb-912f-b507ee15e33e.png">

When playing
<img width="897" alt="Screenshot 2021-07-12 at 10 04 30" src="https://user-images.githubusercontent.com/2813677/125264322-a8b47700-e2fb-11eb-8397-075937b777f7.png">

What the request in red was
<img width="569" alt="Screenshot 2021-07-12 at 10 03 43" src="https://user-images.githubusercontent.com/2813677/125264327-ab16d100-e2fb-11eb-9bdf-8a60d4c1bcb6.png">

#### 2. When the video fails

After page load
<img width="1067" alt="Screenshot 2021-07-12 at 10 26 14" src="https://user-images.githubusercontent.com/2813677/125264311-a6521d00-e2fb-11eb-8203-dae8f2bc036f.png">

Reproducing that 3rd call on the Console
<img width="1058" alt="Screenshot 2021-07-12 at 10 06 00" src="https://user-images.githubusercontent.com/2813677/125264315-a7834a00-e2fb-11eb-8b73-bff9ba2f5d86.png">

**Comment by andrewcatalpa** [comment]
Hi Team, just noting that we're still getting pressure from JID / ACEM on when we might be able to fix this bug on Safari Playback on Bero; 
![IMG_2053_1](https://user-images.githubusercontent.com/86705107/126119278-76deb28a-d06a-4749-822a-c58ffcdd3c00.PNG)

**Comment by pedro16v** [comment]
@andrewerbs this has been tested and it's now working on staging. Peter will deploy to production soon!
