### ISSUE TITLE
Raise quality for video thumbnail images

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#886]
Following up on a reported issue about the video preview having low quality, I found that we're generating very small images that will make its compression rather evident.

Note how we're generating a `101x180px` image to cover a `270x480px` video.

Can we raise the quality?

* The card: https://pacificlearn.io/#/site/pep-learning-activities/microorganisms/introducing-bacteria-and-viruses/sharing-and-re-capping-learning-outcomes:7:plan
* The video: https://admin.pacificlearn.io/media/media_transcodes/20-H264-480p-20q.qxeau5jf.mp4
* The thumbnail: https://admin.pacificlearn.io/media/media/20_thumb_hc62x51s.jpg

**Comment by boerwastaken** [comment]
Compression artefacts (such as jpeg ringing aka "wrinkles") and pixelation caused by upscaling are orthogonal.

> Can we raise the quality?

We can raise the *quantity* of pixels which will reduce upscaling pixelation, which most people will perceive as "better quality" :clown_face: 

We can do so either through altering the default [which was set to 180px height on April 22nd](https://github.com/catalpainternational/canoe-backend/commit/f8469b9003c8b6db8b09f91e34ba3faf7b84a12d) following [design instructions for 180px height](https://github.com/catalpainternational/canoe/issues/594#issuecomment-819225526), or through setting it on a per-deployment basis in the deployment configuration.

Probably best to bump the default. What should it be bumped to? 360 pixels should be enough for everyone!

**Comment by pedro16v** [comment]
Thanks for referring back to the original design consideration. There's a double problem here. One is that we're generating a thumbnail thinking of landscape image ratios only (hence the fixed 180px height). The other is that we're not limiting the video component's height to 180px, letting it take as much vertical space as it needs.

Let's look at what I'm talking about

**A** — Video as currently displayed
**B** — Video if limited to a height of 180px
**C** — Same as **B** but showing video controls

| A | B | C | 
| - | - | - |
<img width="375" alt="Screenshot 2021-07-29 at 09 39 42" src="https://user-images.githubusercontent.com/2813677/127460931-3008bafa-7c9e-448f-b9b0-504958ff9a88.png"> | <img width="375" alt="Screenshot 2021-07-29 at 09 40 13" src="https://user-images.githubusercontent.com/2813677/127460920-c7c4d354-5ea3-4201-a969-b013f1bc55b1.png"> | <img width="375" alt="Screenshot 2021-07-29 at 09 40 50" src="https://user-images.githubusercontent.com/2813677/127460900-31e4ea6e-f758-4fac-8f12-06d4bb5ac53f.png">

Obviously that option **B** makes the video ridiculously small due to its format but there's always the option to watch it in full screen on the device.

This being said, and regardless of our decision on limiting the height or not, what would be the best option to create an adequate thumbnail?
