### ISSUE TITLE
I can edit my own comments

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#901]
Follow up from #770 

## Conditions of Satisfaction
- [x] I have the option to edit my own comments
- [x] Saving the edited comment updates the interface
  - [x] Edited comments are marked as such ('Edited')
- [ ] Content managers have access to the editing history

**Comment by pedro16v** [comment]
@andrewwapling do we also have a design for edition of comments? I feel like I've asked this somewhere also but lost track.

**Comment by andrewwapling** [comment]
@pedro16v not as yet this will require design :)

**Comment by andrewwapling** [comment]
Hi @pedro16v @Juliana-t @megganeturner I've created a design direction for the editing comments.

Kindly see screen break down and walk through below:

===

1. Example of a discussion screen with your own comment (MT Yellow Avatar). An Edit option appears to the left of the Delete option. Click Edit – https://invis.io/4N10MWTLADZM#/448759615_Course_Detail_-_Discussion_-_Posted
2. Edit comment screen surfaces for a user to edit their own comment (you'll need to scroll down due to Invision limitations however the actual experience would deliver users to the top of white edit pane). Once a user starts to edit the comment by tapping into and focusing on the comment field the inactive state of the button transitions to active blue – https://invis.io/4N10MWTLADZM#/457645603_Course_Detail_-_Discussion_-_Edit_Comment_-_Inactive
3. Edit comment screen as above showing field focus state and post updated comment CTA button active state – https://invis.io/4N10MWTLADZM#/457645604_Course_Detail_-_Discussion_-_Edit_Comment
4. Dismissable toast notification confirmation and edited comment state – https://invis.io/4N10MWTLADZM#/457645605_Course_Detail_-_Discussion_-_Comment_Edited

===

Hope you like! Let me know if you have any queries or feedback on the proposed design direction :)

**Comment by pedro16v** [comment]
Seen on JID staging. Trying to save an edited comment is causing an error.

1. Click on "Post updated comment"
2. See error.


![Screenshot 2021-09-30 at 09 09 30](https://user-images.githubusercontent.com/2813677/135400201-e5c74324-1bdc-485f-8cd7-e6cb4485f1fb.png)

![Screenshot 2021-09-30 at 09 09 45](https://user-images.githubusercontent.com/2813677/135400215-d81dd4f3-0b38-4af8-b147-10a5a1ad5fcf.png)

**Comment by md8n** [comment]
This is now all in: https://github.com/catalpainternational/bero/pull/269

@pedro16v - Please raise any residual aspects of this issue as new issue(s) in catalpa/bero and close this issue

**Comment by md8n** [comment]
> Seen on JID staging. Trying to save an edited comment is causing an error.
> 
> 1. Click on "Post updated comment"
> 2. See error.
> 
> ![Screenshot 2021-09-30 at 09 09 30](https://user-images.githubusercontent.com/2813677/135400201-e5c74324-1bdc-485f-8cd7-e6cb4485f1fb.png)
> 
> ![Screenshot 2021-09-30 at 09 09 45](https://user-images.githubusercontent.com/2813677/135400215-d81dd4f3-0b38-4af8-b147-10a5a1ad5fcf.png)

@pedro16v - I can't repeat this (tested with jid-staging) - can you please confirm yourself.
Also still need the residual parts of this issue on catalpa/bero and this issue formally closed.

**Comment by pedro16v** [comment]
Yep, solved.
