### ISSUE TITLE
I can delete my own comments

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#902]
Follow up from #770

## Conditions of satisfaction

- [ ] I have the option to delete my own comments
- [ ] Deleting my comment updates the interface
  - [ ] A placeholder will inform other users about the deleted comment
  - [ ] A toast message will inform me about the success of the operation
- [ ] Content managers have access deleted comments (on Wagtail)

## Resources

* Explore the Invision [prototype](https://projects.invisionapp.com/share/4N10MWTLADZM#/screens/449199854)

A — Deleting a first level reply (note the confirmation toast)
B — Deleting a second level reply
C — Confirmation modal

| A | B | C |
| - | - | - |
<img width="320" alt="Screenshot 2021-08-13 at 12 56 47" src="https://user-images.githubusercontent.com/2813677/129354525-dcfd0409-31a0-473d-94d4-356c57ab1df5.png"> | <img width="320" alt="Screenshot 2021-08-13 at 13 00 30" src="https://user-images.githubusercontent.com/2813677/129354480-e8ec047f-9365-4465-9a78-0aee7129d59c.png"> | <img width="320" alt="Screenshot 2021-08-13 at 12 59 07" src="https://user-images.githubusercontent.com/2813677/129354495-7b345485-0c83-45e3-9143-b92640493001.png">

**Comment by pedro16v** [comment]
@andrewwapling i believe the "A placeholder will inform other users about the deleted comment" requirement is a new thing. What do you think about this? The rationale here is to let users know that content was previously there which could explain oddness on the chain of comments.

Note for developers: if there's no design for a placeholder, we could start by simply hiding the deleted comment.

**Comment by andrewwapling** [comment]
Hi @pedro16v thanks for setting this up. Please see proposed design for the deleted comment alert:

https://invis.io/JF11HW55SZRX

Kindly review and let me know if you're happy with this approach.

**Comment by pedro16v** [comment]
I'm pulling this one to the backlog while we resolve [this ongoing discussion](https://projects.invisionapp.com/share/JF11HW55SZRX#/screens/454656278/comments/144634574) on InVision.

**Comment by andrewwapling** [comment]
Hi @pedro16v pulling this one back in from Invision as promised please see below x3 scenarios for consideration:

1. Alert (show general alert in thread to all users letting them know a comment has been deleted) – https://invis.io/AZ11IPABU43C
2. Alert w/ avatar & name (show user identified alert in thread to all users letting them know a comment has been deleted) – https://invis.io/CN11IPADK2GX
3. No Alert (simply hide the deleted comment from thread for all users once a comment has been removed) – https://invis.io/JF11HW55SZRX

I feel there is merit in the simple option of purely hiding the deleted comment (option 3.). This being said in a thread context it could be useful to display a general alert so that people understand any potentially disjointed conversation (option 1.). My only concerns with the avatar and name approach is that it could identify someone who doesn't need to be identified and that it does take up valuable screen real estate for not much user gain. 

Kindly review and let me know your thoughts and preferences.

**Comment by pedro16v** [comment]
@andrewwapling — would the scenario below be valid too? This would be a first level response that has two second level replies under it. The original response is later removed by the author.

<img width="363" alt="Screenshot 2021-08-10 at 10 22 22" src="https://user-images.githubusercontent.com/2813677/128842493-58eb807b-5647-435e-b51e-80adc451836c.png">

**Comment by Juliana-t** [comment]
I prefer solution 1 - Alert (show general alert in thread to all users letting them know a comment has been deleted) – https://invis.io/AZ11IPABU43C
Also wondering if for when a user flags a comment (hiding that comment for him) or when a comment is deleted by a moderator, should a similar information/box be presented? I know this is a different issue, but good to consider in terms of consistency of the UI/UX
About Pedro's question on when there is a thread, I think this would work. Any suggestions or considerations @andrewwapling ?

**Comment by andrewwapling** [comment]
@pedro16v good pickup re: top level thread scenario. Yes, I would see this scenario following the same pattern, please see design reference: https://invis.io/4N10MWTLADZM#/456766240_Course_Detail_-_Discussion_-_Comment_Deleted_Alert_-_Top_Level

@Juliana-t  good pickup re: inappropriate flag. Likewise I would see this following the same alert notification element, please see design direction: https://invis.io/4N10MWTLADZM#/450357114_Course_Detail_-_Discussion_-_Inappropriate_Notification

My preferred approach is also the original option 1. alert notification style, please see recommended design direction: https://invis.io/4N10MWTLADZM

**Comment by pedro16v** [comment]
Great. I think we can work with this! Thanks all.

**Comment by andrewwapling** [comment]
Hi @pedro16v excellent! Thanks for confirming :)

**Comment by pedro16v** [comment]
First post updated with screenshots from the latest design and updated InVision prototype link.
