### ISSUE TITLE
Make Available Offline: Feedback

### ISSUE THREAD

**Issue by PeteCoward** [catalpainternational/canoe#908]
The make available offline buttons provide no feedback for users that they have been clicked, I'm not sure we have design for this, but typically we would "disable" the button (if it is a button) or hide and show some kind of message "retrieving..."

**Comment by pedro16v** [comment]
I'm also seeing that we're not showing the correct state when clicking "Make Offline". 

The content downloads, I can use it offline but it still shows the "Make Offline" action. Curiously enough, the first Activity is marked as "Available Offline"

https://user-images.githubusercontent.com/2813677/128343354-7af47903-c6ea-4b3a-af08-b3210697c0e1.mov

**Comment by pedro16v** [comment]
Please check these recommendations from Andy regarding loading progress https://github.com/catalpainternational/canoe/issues/912#issuecomment-893942475

**Comment by pedro16v** [comment]
I have updated the original post with design information.

Implementation seems correct except for Courses which are still missing the new circle around the download arrow.

---

**We have this**
<img width="375" alt="Screenshot 2021-08-11 at 13 59 02" src="https://user-images.githubusercontent.com/2813677/129033055-64390b21-468a-46b6-a3d0-1bd9ca7b377d.png">

**But should have this**
| Before download | Downloading | Downloaded |
| - | - | - |
<img width="60" alt="Screenshot 2021-08-11 at 13 50 15" src="https://user-images.githubusercontent.com/2813677/129033100-a43facec-46e1-4f61-a732-0baaa848c7c4.png"> | <img width="60" alt="Screenshot 2021-08-11 at 13 50 29" src="https://user-images.githubusercontent.com/2813677/129033098-acd27625-a388-408b-aba3-f9c07a1cf977.png"> | <img width="60" alt="Screenshot 2021-08-11 at 13 50 38" src="https://user-images.githubusercontent.com/2813677/129033096-2a8930f4-f7ac-4084-aba6-895d45efe90c.png">

**Notes:**
* There's no reason to hold a release because of this but it would be nice to fix it
* The file size under the icon is a new element. If it takes more than `minutes` to do, we should leave as it is (no text)
* The file sizes on the examples are from different files, which explains why the value changes. It is not supposed to be a progress indicator.

---

This way we can match the new implementation, already visible for Resources and Teaching Activities

| Resources | Teaching |
| - | - |
<img width="375" alt="Screenshot 2021-08-11 at 13 58 35" src="https://user-images.githubusercontent.com/2813677/129033380-247c2b27-b482-4393-9f04-e1ba9ec67d24.png"> | <img width="374" alt="Screenshot 2021-08-11 at 13 58 19" src="https://user-images.githubusercontent.com/2813677/129033384-4376b119-e798-419b-ba98-bc37f78d3d76.png">
