### ISSUE TITLE
While setting up my account, I am asked to provide demographic details

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#926]
## Overview
Partners using Bero often need to collect some personal data for reporting. This is currently being added by admins as they add users. We want this data to be entered by the user. We want this data to be entered by the user when they set up their account.

## Conditions of satisfaction
- [ ] This only applies to users registering an account (not to guests)
- [ ] One or more screens containing demographic questions will show after the user agrees with the Privacy Consent screen.
  - [ ] These cards are optional. A Bero instance can be set to have them or not.
- [ ] Data to be collected will depend on the requirements of each project using Bero
  - [ ] Each instance of Bero can be configured with their own user attributes.
  - [ ] These are configured in Wagtail
  - [ ] All answers are available as options that can be set on Wagtail
- [ ] User attribute fields can be set to required or not.
- [ ] Each instance of Bero can have up to 15 user attributes.
- [ ] Each onboarding card can have up to 3 fields for attributes
- [ ] Details can still be collected if user is offline
- [ ] User attributes selected as part of the onboarding process can be seen (but not edited) through the profile page
- [ ] After completing this process, the account can:
  - [ ] Enter a pending state (check User Story)
  - [ ] Be ready to use

## Design resources
- [Invision](https://projects.invisionapp.com/d/main#/console/21662041/461033728/preview)

**Comment by andrewwapling** [comment]
Hi @pedro16v thanks for setting this one in play.

As promised I've worked up high fidelity visual designs and flow for this, please see main prototype link:

https://invis.io/TD11LKX49SYP

Please also see screen breakdown below:

===

**Login**
1. Login (at login a user will be presented with a card view that prompts users to fill additional demographic details): https://invis.io/F311LKXAP27M

**Demographic Onboarding** 
1a. 1st Card - Prompts  users to fill additional detail and communicates value of doing so on first login. Users can't progress if they haven't filled mandatory fields: https://invis.io/W511LKXEFCPZ
1b. 1st Card  - Showing drop down selected state and active pagination button state: https://invis.io/P211LKXFEVU4
1c. 2nd Card - Showing validation states: https://invis.io/YR11LKXG8HN5
1d. 2nd Card - Showing filled state and active pagination button state: https://invis.io/8N11LKXN6PQG
2. Success Confirmation - Alerting users that they have completed the flow and prompt to commence learning which delivers them to their home screen via button CTA: https://invis.io/PX11LKXP8U2H

**Home**
1. Home - Users are delivered to the home screen via the confirmation CTA once they have successfully onboarded: https://invis.io/3B11LKXR6Y5P

Please note: the design intention is for all cards to scroll within the viewport height of the card and present a scroll handle as per design if content doesn't fit vertically within the card height. Design direction example here: https://invis.io/KM11LKYH8QRP

Re: card scroll there has been discussions in the past of making this more immersive and adding a full screen interaction upon long scroll that will give users more vertical real estate (think Safari iOS browser where bottom browser controls and address bar are hidden on the downward scroll). I'm not sure that this is the correct place for it however the concept is linked so thought I would raise this one again here for FED implementation consideration. Please see some design direction here: 

Long scroll (for example half viewport height) whereby card and content transitions to full height and width and progress bar disappears out of view and the pagination is houses on top of content with a fade): https://invis.io/A411LKYUGEVC

Longer scroll (for example double+ the viewport height) whereby card and content transitions to full height and width and progress bar and pagination disappears out of view): https://invis.io/NQ10AF62GVCR

The intended behaviour would be inverse to the above approach whereby any upward scroll above say 200px in height would transition the card layout back into view, show the progress bar and the standard pagination controls. The effect would give the user a sense of immersion in the content within the card and a sense of focus where card content is lengthy.

Let me know your thoughts on this approach? It may require some FE effort to finesse, however I feel the results for a user would be really valuable. It would also create a sense of depth and finesse overall interaction with the app.

===

**Comment by andrewwapling** [comment]
Hi @pedro16v further to the above I've created an uplifted demographic onboarding design based on the new global onboarding card style seen here: https://invis.io/R811NG3VAEWS

Uplifted demographic onboarding: https://invis.io/TD11LKX49SYP

The main rationale as per the global onboarding card style change was to create a pattern distinct from the activity cards for any onboarding, helper or tip content.

Kindly review and look forward to hearing any feedback or queries on these recommendations.

**Comment by Juliana-t** [comment]
@andrewwapling should we wait for the prototype of the broader login/account creation process that we are designing before moving forward with this? Just keeping in mind that we may have some changes on this initial proposal, based on what we discussed and learned during the design session

**Comment by andrewwapling** [comment]
Hi @Juliana-t yes I tend to agree, if we have time it could be beneficial to review and implement in context of the wider social auth, login, rego experience. If we really need to get this in earlier though I don't see too much of an issue with backtracking on implementation as it follows on quite closely with current state design recommendations for the demographic and standard onboarding patterns.

**Comment by md8n** [comment]
> Each instance of Bero can be configured with their own user attributes. These are configured in Wagtail
 
I would recommend against this - These fields need to be set to match policy, there is also a likelihood of government legislation involved here. So while they should be configurable, being changeable through the wagtail admin is almost certainly undesirable. Specialist wagtail groups would allow for this, but currently they're just not well handled to the degree that the use of wagtail groups to control who can make changes to this very special set of information is very undesirable.

> Each instance of Bero can have up to 15 user attributes.

Where did this number come from?

> Details can still be collected if user is offline

This is not a reasonable requirement. User account creation and onboarding require internet access anyway. Recommend that this requirement is dropped at a minimum and preferably that it is restated as "User MUST be online to complete onboarding"

> User attributes selected as part of the onboarding process can be seen (but not edited) through the profile page

Why this requirement? It doesn't seem to make any sense. Why can't users update their own details?

**Comment by Juliana-t** [comment]
> > Each instance of Bero can be configured with their own user attributes. These are configured in Wagtail
> 
> I would recommend against this - These fields need to be set to match policy, there is also a likelihood of government legislation involved here. So while they should be configurable, being changeable through the wagtail admin is almost certainly undesirable. Specialist wagtail groups would allow for this, but currently they're just not well handled to the degree that the use of wagtail groups to control who can make changes to this very special set of information is very undesirable.

Yes, policy and other legislation around this aspects will be handled by the program, so it is reviewed and decided outside of the platform. What we have been doing and what we want to continue offering, is the following: program team defines attributes they need for their programs (after consultation with engineering and product), engineering sets up those attributes for the Bero instance, certain users (admin) can add and edit values for each attribute through Wagtail. So the admins (usually those are the elearning specialist of that program/team) will be able to change values for each attribute, but not adding or removing attributes. If they need some change regarding attributes (add a new one, lets say 'English literacy') they will need make that request to the engineering team.
Is that clearer now?

> 
> > Each instance of Bero can have up to 15 user attributes.
> 
> Where did this number come from?
This was a product and design decision informed by programs. Although our recommendations is no more than 5 attributes, but we want to provide flexibility here. Especially as some attributes will be optional and some other compulsory to enroll in the training program.
> 
> > Details can still be collected if user is offline
> 
> This is not a reasonable requirement. User account creation and onboarding require internet access anyway. Recommend that this requirement is dropped at a minimum and preferably that it is restated as "User MUST be online to complete onboarding"

The idea was to allow users to complete the demographic details (not the account creation) when they are offline, similar to what we do with completing a lesson or a course, we would collect the information on the device and it will be submitted to the server once the device goes online.
When you say onboarding requires internet access is that because we would have to download the onboarding cards to the device? If so, can't that be done when the user is online and registering their account?
If there is any issue with achieving this requirement, please let me know so we can discuss options.

> 
> > User attributes selected as part of the onboarding process can be seen (but not edited) through the profile page
> 
> Why this requirement? It doesn't seem to make any sense. Why can't users update their own details?
Again, this is program requirement - both on KHS and ACIAR. While you may think that all attributes should be editable by the user, the reality is that there are cases where the approval and M&E may require that the a value for a specific attribute is verified by program staff. An example could be, teachers are required to complete certain course, for M&E and certifications (to be prepared outside of Bero), we are using an attribute 'Role' and value 'teacher' to see what users are teachers. We can't risk having someone going to their profile and changing the role to 'admin', either by mistake or just because they are playing around. That is why we decided, with the edu team, that compulsory attributes can't be modified by a user (after account registration) through the UI. We ask them to get in touch with the support team, and the support team will be responsible to verify that information (Example, someone moved to a new position) and do the modification through the CMS

**Comment by md8n** [comment]
> Is that clearer now?

Yes

> The idea was to allow users to complete the demographic details (not the account creation) when they are offline, similar to what we do with completing a lesson or a course, we would collect the information on the device and it will be submitted to the server once the device goes online.
When you say onboarding requires internet access is that because we would have to download the onboarding cards to the device? If so, can't that be done when the user is online and registering their account?
If there is any issue with achieving this requirement, please let me know so we can discuss options.

The process is currently:
* User creates an account for themselves (they have to be online for this)
* They login with their new credentials (we assume that this is immediately after the above step, so they'll still be online)
* They are forced to the Privacy Consent Page
* After consenting they are forced to the first Onboarding page

There are no 'onboarding cards' per se.

User account creation, onboarding, and wagtail admin definitions for the user attributes are all controlled through settings. This could be retrieved as a larger lump of info (one for account creation, and another for privacy consent and onboarding), but it hasn't been built that way, and would require refactoring to support it. i.e. time.

> > Why this requirement? It doesn't seem to make any sense. Why can't users update their own details?

> Again, this is program requirement - both on KHS and ACIAR. While you may think that all attributes should be editable by the user, the reality is that there are cases where the approval and M&E may require that the a value for a specific attribute is verified by program staff. An example could be, teachers are required to complete certain course, for M&E and certifications (to be prepared outside of Bero), we are using an attribute 'Role' and value 'teacher' to see what users are teachers. We can't risk having someone going to their profile and changing the role to 'admin', either by mistake or just because they are playing around. That is why we decided, with the edu team, that compulsory attributes can't be modified by a user (after account registration) through the UI. We ask them to get in touch with the support team, and the support team will be responsible to verify that information (Example, someone moved to a new position) and do the modification through the CMS

So what we're describing here is that users get to make a selection initially when they go through onboarding, but that selection is later verified / approved by program staff. However, the demographic fields (names, email address, gender, age bracket) should always be editable by users. Some information is 'owned' by the users, and some by the program.

Also what fields are shown to the user for account creation,  onboarding and the user details page are strictly 'opt-in' via the settings.

Note that some fields are 'banned' from ever being made available to users on the front end, even if one of us makes a mistake and adds them to the settings. These are `is_active` and `is_superuser`.

**Comment by Juliana-t** [comment]
@md8n
- **onboarding demographic cards when online only** - that is fine for now, on a future release we may (or not) want to explore the option to allow for this to be completed when offline. For now lets not put more efforts in this
- demographic details not editable after account approval - exactly as you described, users can select it initially but some won't be possible to change later on (after approval) through the user profile page, as you said, some information is _owned_ by the user, some by the program

Please let me know if there are still questions that aren't clear

**Comment by andrewwapling** [comment]
@Juliana-t @md8n was there any extra design work required here or do you have all the assets you need?

**Comment by md8n** [comment]
@andrewwapling I'm pretty sure that no extra design work is required here. I would assume that, per bero implementation, we may want different imagery for each onboarding page, but the structure of that page I believe is covered.

**Comment by andrewwapling** [comment]
Thanks for confirming @md8n. Regarding illustration work we have a range of core options that @DanielHeads has been working on that we can choose from and adjust if needed to suit the content of the card. Alternatively if the content isn't covered by existing core illustrations we may need to create new illustration/s to suit.

**Comment by Juliana-t** [comment]
@ellijayne @md8n here are the illustrations that Daniel prepared for the demographic details onboarding cards:
[Onborading user details svg](https://drive.google.com/file/d/16YGj698IvsU203BHfXbOSA_al_ZQCDev/view?usp=sharing) 1 
And [illustration for the screen](https://drive.google.com/file/d/16hEWippcRbYhNxI08wnWY5PXErl2FXWU/view?usp=sharing) that is shown after the user completed all onboarding demographic cards.
Please let me know if you have any questions

@andrewwapling later when you have time, not urgent, can you please update the prototype on invision with these illustrations? Thanks!

**Comment by andrewwapling** [comment]
Hi @Juliana-t yes no worries, I'll aim to get these screen designs updated with the new core illustrations shortly. I'll post back with the updated link once complete.

**Comment by andrewwapling** [comment]
Hi @Juliana-t just confirming the Account Creation prototype has been updated with the new core illustrations for onboarding: https://invis.io/FG12IC6DCA5J

**Comment by Juliana-t** [comment]
Perfect! thanks so much Andy. @ellijayne if there is any outstanding questions or any visual asset missing, please let us know and we will get you what you need :)

**Comment by joanico** [comment]
According to the last prototype, it seems to work on PeP staging now.
